// Code generated by MockGen. DO NOT EDIT.
// Source: helpers.go
//
// Generated by this command:
//
//	mockgen -source=helpers.go -destination=./postgres_mocks_test.go -package=postgres_test
//

// Package postgres_test is a generated GoMock package.
package postgres_test

import (
	context "context"
	reflect "reflect"

	v5 "github.com/jackc/pgx/v5"
	pgconn "github.com/jackc/pgx/v5/pgconn"
	postgres "github.com/modulix-systems/goose-talk/postgres"
	gomock "go.uber.org/mock/gomock"
)

// MockqueryBuilder is a mock of queryBuilder interface.
type MockqueryBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockqueryBuilderMockRecorder
	isgomock struct{}
}

// MockqueryBuilderMockRecorder is the mock recorder for MockqueryBuilder.
type MockqueryBuilderMockRecorder struct {
	mock *MockqueryBuilder
}

// NewMockqueryBuilder creates a new mock instance.
func NewMockqueryBuilder(ctrl *gomock.Controller) *MockqueryBuilder {
	mock := &MockqueryBuilder{ctrl: ctrl}
	mock.recorder = &MockqueryBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockqueryBuilder) EXPECT() *MockqueryBuilderMockRecorder {
	return m.recorder
}

// ToSql mocks base method.
func (m *MockqueryBuilder) ToSql() (string, []any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToSql")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ToSql indicates an expected call of ToSql.
func (mr *MockqueryBuilderMockRecorder) ToSql() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToSql", reflect.TypeOf((*MockqueryBuilder)(nil).ToSql))
}

// MockQueryable is a mock of Queryable interface.
type MockQueryable struct {
	ctrl     *gomock.Controller
	recorder *MockQueryableMockRecorder
	isgomock struct{}
}

// MockQueryableMockRecorder is the mock recorder for MockQueryable.
type MockQueryableMockRecorder struct {
	mock *MockQueryable
}

// NewMockQueryable creates a new mock instance.
func NewMockQueryable(ctrl *gomock.Controller) *MockQueryable {
	mock := &MockQueryable{ctrl: ctrl}
	mock.recorder = &MockQueryableMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryable) EXPECT() *MockQueryableMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockQueryable) Exec(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range arguments {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockQueryableMockRecorder) Exec(ctx, sql any, arguments ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, arguments...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockQueryable)(nil).Exec), varargs...)
}

// Query mocks base method.
func (m *MockQueryable) Query(ctx context.Context, sql string, args ...any) (v5.Rows, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].(v5.Rows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockQueryableMockRecorder) Query(ctx, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockQueryable)(nil).Query), varargs...)
}

// QueryRow mocks base method.
func (m *MockQueryable) QueryRow(ctx context.Context, sql string, args ...any) v5.Row {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRow", varargs...)
	ret0, _ := ret[0].(v5.Row)
	return ret0
}

// QueryRow indicates an expected call of QueryRow.
func (mr *MockQueryableMockRecorder) QueryRow(ctx, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRow", reflect.TypeOf((*MockQueryable)(nil).QueryRow), varargs...)
}

// MockReleaseable is a mock of Releaseable interface.
type MockReleaseable struct {
	ctrl     *gomock.Controller
	recorder *MockReleaseableMockRecorder
	isgomock struct{}
}

// MockReleaseableMockRecorder is the mock recorder for MockReleaseable.
type MockReleaseableMockRecorder struct {
	mock *MockReleaseable
}

// NewMockReleaseable creates a new mock instance.
func NewMockReleaseable(ctrl *gomock.Controller) *MockReleaseable {
	mock := &MockReleaseable{ctrl: ctrl}
	mock.recorder = &MockReleaseableMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReleaseable) EXPECT() *MockReleaseableMockRecorder {
	return m.recorder
}

// Release mocks base method.
func (m *MockReleaseable) Release() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Release")
}

// Release indicates an expected call of Release.
func (mr *MockReleaseableMockRecorder) Release() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockReleaseable)(nil).Release))
}

// MockAcquirable is a mock of Acquirable interface.
type MockAcquirable struct {
	ctrl     *gomock.Controller
	recorder *MockAcquirableMockRecorder
	isgomock struct{}
}

// MockAcquirableMockRecorder is the mock recorder for MockAcquirable.
type MockAcquirableMockRecorder struct {
	mock *MockAcquirable
}

// NewMockAcquirable creates a new mock instance.
func NewMockAcquirable(ctrl *gomock.Controller) *MockAcquirable {
	mock := &MockAcquirable{ctrl: ctrl}
	mock.recorder = &MockAcquirableMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAcquirable) EXPECT() *MockAcquirableMockRecorder {
	return m.recorder
}

// Acquire mocks base method.
func (m *MockAcquirable) Acquire(ctx context.Context) (postgres.Queryable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Acquire", ctx)
	ret0, _ := ret[0].(postgres.Queryable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Acquire indicates an expected call of Acquire.
func (mr *MockAcquirableMockRecorder) Acquire(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Acquire", reflect.TypeOf((*MockAcquirable)(nil).Acquire), ctx)
}
